### ISSUE TITLE
0.9.4 still doesn't work with Jackson 2.9.0

### ISSUE THREAD

**Issue by stevenschlansker** [HubSpot/jackson-datatype-protobuf#18]
```
Caused by: java.lang.NoSuchMethodError: com.hubspot.jackson.datatype.protobuf.ProtobufDeserializer._parseInteger(Lcom/fasterxml/jackson/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/lang/Integer;
	at com.hubspot.jackson.datatype.protobuf.ProtobufDeserializer.readValue(ProtobufDeserializer.java:206)
```

I started hacking on a fix for it, got most tests except arrays working and gave up.  Here's what I had so far in case it comes in useful:

```diff
diff --git a/pom.xml b/pom.xml
index 3afc4f3..cb60e3a 100644
--- a/pom.xml
+++ b/pom.xml
@@ -21,6 +21,10 @@
       <tag>HEAD</tag>
   </scm>
 
+    <properties>
+      <dep.jackson.version>2.9.0</dep.jackson.version>
+    </properties>
+
     <developers>
         <developer>
             <name>Jonathan Haber</name>
diff --git a/src/main/java/com/hubspot/jackson/datatype/protobuf/ProtobufDeserializer.java b/src/main/java/com/hubspot/jackson/datatype/protobuf/ProtobufDeserializer.java
index 01bf51d..56b6c8e 100644
--- a/src/main/java/com/hubspot/jackson/datatype/protobuf/ProtobufDeserializer.java
+++ b/src/main/java/com/hubspot/jackson/datatype/protobuf/ProtobufDeserializer.java
@@ -180,13 +181,11 @@ public class ProtobufDeserializer<T extends Message> extends StdDeserializer<Mes
     }
   }
 
-  private Object getNullValue(JavaType type, Object nullValue, DeserializationContext context) throws JsonProcessingException {
-    if (type.isPrimitive() && context.isEnabled(DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES)) {
-      throw context.mappingException("Can not map JSON null into type %s"
-          + " (set DeserializationConfig.DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES to 'false' to allow) -- "
-          + type.getRawClass().getName());
+  private void checkNullReturn(FieldDescriptor field, DeserializationContext context) throws JsonProcessingException {
+    if (context.isEnabled(DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES)) {
+      throw context.mappingException("Can not map JSON null into primitive field " + field.getFullName()
+          + " (set DeserializationConfig.DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES to 'false' to allow)");
     }
-    return nullValue;
   }
 
   private Object readValue(Message.Builder builder, FieldDescriptor field, Message defaultInstance, JsonParser parser,
@@ -201,41 +200,35 @@ public class ProtobufDeserializer<T extends Message> extends StdDeserializer<Mes
       }
     }
 
+    if (parser.getCurrentToken() == JsonToken.VALUE_NULL) {
+        switch (field.getJavaType()) {
+        case INT:
+        case LONG:
+        case FLOAT:
+        case DOUBLE:
+        case BOOLEAN:
+            checkNullReturn(field, context);
+            // fall through
+        default:
+            return null;
+        }
+    }
+
     switch (field.getJavaType()) {
       case INT:
-        value = _parseInteger(parser, context);
-
-        if (value == null) {
-          getNullValue(SimpleType.construct(Integer.TYPE), 0, context);
-        }
+        value = _parseIntPrimitive(parser, context);
         break;
       case LONG:
-        value = _parseLong(parser, context);
-
-        if (value == null) {
-          getNullValue(SimpleType.construct(Long.TYPE), 0L, context);
-        }
+        value = _parseLongPrimitive(parser, context);
         break;
       case FLOAT:
-        value = _parseFloat(parser, context);
-
-        if (value == null) {
-          getNullValue(SimpleType.construct(Float.TYPE), 0.0f, context);
-        }
+        value = _parseFloatPrimitive(parser, context);
         break;
       case DOUBLE:
-        value = _parseDouble(parser, context);
-
-        if (value == null) {
-          getNullValue(SimpleType.construct(Double.TYPE), 0.0d, context);
-        }
+        value = _parseDoublePrimitive(parser, context);
         break;
       case BOOLEAN:
-        value = _parseBoolean(parser, context);
-
-        if (value == null) {
-          getNullValue(SimpleType.construct(Boolean.TYPE), false, context);
-        }
+        value = _parseBooleanPrimitive(parser, context);
         break;
       case STRING:
         switch (parser.getCurrentToken()) {

```

**Comment by cowtowncoder** [comment]
One thing that could be useful for README would be to indicate known good versions (and in cases where known, problematic ones)?

Let me know if I can help with specific mapping of methods. This area did change quite a bit due to stricter enforcement of null/coercion checks, attempts at unifying error messaging and such.

**Comment by jhaber** [comment]
I can try to set up a bunch of travis builds to verify compatibility, and add the version ranges to the readme

**Comment by cowtowncoder** [comment]
@jhaber that would be great, but even something as simple as noting down noted versions.

I don't know if it'd be of use, but there's also this:

https://github.com/cowtowncoder/jackson-compat-minor

which could provide some value... I haven't quite figured out good way to use it but it seemed like a worthy idea in general. Could maybe add this project too... mostly help with new Jackson core version development.

**Comment by jhaber** [comment]
I got the travis build set up with Jackson 2.3.x through 2.9.x The results are [here](https://travis-ci.org/HubSpot/jackson-datatype-protobuf/builds/275556562). It looks like all tests pass with Jackson 2.3.x-2.6.x. A few test failures with Jackson 2.7.x-2.8.x. Doesn't compile against Jackson 2.9.x. I added a note to this effect to the README https://github.com/HubSpot/jackson-datatype-protobuf/commit/594d89671234b8b4c0621081dcce23e9535593b1

I'll work on getting the build passing against all the versions there and update the README as I make progress

**Comment by stevenschlansker** [comment]
Thanks so much!

**Comment by cowtowncoder** [comment]
Excellent!

**Comment by jhaber** [comment]
I fixed the compilation errors and got the broken tests passing on newer versions of Jackson (was just a red herring). I released version 0.9.5 which should be compatible with Jackson 2.9.x, and updated the compatibility chart on the README [here](https://github.com/HubSpot/jackson-datatype-protobuf/blob/master/README.md#jackson-compatibility).

I noticed that there are now lots of deprecated methods being used, so it's likely that things will break with future Jackson releases. But switching to the replacement methods would break compatibility with older versions of Jackson. I can sprinkle lots of try/catch + reflection around to try to make it work with new and old versions of Jackson, but I don't think this is a viable long-term strategy. I'm thinking of maintaining multiple branches targeting specific minor versions of Jackson. For example `jackson26` branch that produces a Maven artifact with version `0.9.6-jackson2.6`. Does this seem reasonable? Since they would all have matching groupId and artifactId, users can use dependency management to make sure they're getting the version of jackson-datatype-protobuf that matches their Jackson version.

**Comment by stevenschlansker** [comment]
That's a reasonable solution for us.  Hopefully the rate of change of the Jackson interface will slow down, this is pretty painful :)

**Comment by cowtowncoder** [comment]
Another possibility could be syncing versions to Jackson versions (2.6.0, 2.7.0 etc), unless there are some other semantic constraints that are more important. I wouldn't necessarily expect following patch levels (more work that way -- although if you did, version could be added in `jackson-bom`), just minor version.

Also: going forward, if breakages are found early enough, I can retrofit missing internal API methods in patch release. I'd rather do that (even if it's not as good as preventing it by deprecating things more slowly) than force narrow set of compatible versions.
So: I'd have been ok adding bridge method back, with deprecation, given that it was in use.
I just do not have means to pro-actively find these cases since they fall in sort of grey area between public API and private methods; inheritance is... tricky to support.

**Comment by jhaber** [comment]
My concern with having the versions synced directly to Jackson versions is that it makes it awkward to add library features and release a new version. For example when we add protobuf3 support that would probably be a major version bump for the library, and it's something where we'd want to cut a new release for all supported Jackson versions. So I think something like `{libraryVersion}-{jacksonVersion}` would work better for our use-case

**Comment by cowtowncoder** [comment]
Yes, there are many aspects to good versioning, and I can see why coupling to one of dependencies has its downsides.

Back to my offer to help with backwards-compatibility from jackson side... do you think number of methods in `StdDeserializer` (etc) might be small enough, that my inclusion of these in 2.9.2 would help reduce need for specific versioning? Although getting that release out will take a while (2.9.1 just went out, so probably ~4 weeks) it might be worth it, if that would then cover wider jackson minore version set.

**Comment by jhaber** [comment]
I don't think it's necessary, it looks like the replacement methods have been present since version 2.2.0 so it should be safe to use those. I made preJackson27, jackson27, jackson28, and jackson29 branches. All but the last should be ready for release.
