### ISSUE TITLE
Provide a version compatible with protobuf 3.22

### ISSUE THREAD

**Issue by atollena** [HubSpot/jackson-datatype-protobuf#99]
Protobuf 3.22 made some changes such that projects that compile with protobuf 3.22 have a compiled version of `Struct.Builder` that is missing a method. The exact error message is the following:

```
java.lang.NoSuchMethodError: 'com.google.protobuf.Struct$Builder com.google.protobuf.Struct$Builder.addRepeatedField(com.google.protobuf.Descriptors$FieldDescriptor, java.lang.Object)'

	at com.hubspot.jackson.datatype.protobuf.builtin.deserializers.StructDeserializer.populate(StructDeserializer.java:28)
```

I have been able to work around this by re-compiling jackson-datatype-protobuf against with a dependency on protobuf 3.22 rather than 3.19.

Would you be open to publishing a new version of jackson-datatype-protobuf with an updated version of protobuf? The latest version of grpc-java uses protobuf 3.22, which makes it somewhat difficult to keep compatibility between latest grpc versions (>1.55.1) and still use `jackson-datatype-protobuf`.

**Comment by atollena** [comment]
(see this issue on grpc-java: https://github.com/grpc/grpc-java/issues/10320)

**Comment by atollena** [comment]
I think I figured out exactly why `NoSuchMethod` is raised in the current library version that is compiled with protobuf 3.19 on messages compiled with 3.22, and compiling this library with protobuf 3.22 fixes the problem:

- jackson-datatype-protobuf calls addRepeatedFields here: https://github.com/HubSpot/jackson-datatype-protobuf/blob/master/src/main/java/com/hubspot/jackson/datatype/protobuf/builtin/deserializers/StructDeserializer.java#L28
- The method invoked has signature
  -  `(Lcom/google/protobuf/Descriptors$FieldDescriptor;Ljava/lang/Object;)Lcom/google/protobuf/Struct$Builder;` when this library is compiled with protobuf 3.19
  - `(Lcom/google/protobuf/Descriptors$FieldDescriptor;Ljava/lang/Object;)Lcom/google/protobuf/GeneratedMessageV3$Builder` when this library is compiled with protobuf 3.22
- When the generated message has been compiled with 3.19, the current library version works fine because `addRepeatedField` method is implemented directly in the message and has return type `Struct$Builder`
- However, that changed in protobuf 3.22 and messages do not implement this method directly anymore. Instead it is only implemented in the superclass at https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java#L798-L801. The method is implemented in `GeneratedMessageV3`, so it returns `Lcom/google/protobuf/GeneratedMessageV3$Builder`, which does not match the expected invocation signature that returns `Lcom/google/protobuf/Struct$Builder` because the type is wider.
